-- 004-seed-100-more-questions.sql
-- Adds 100 SAT-style questions with detailed explanations.

-- OPTIONAL (only if you want exactly 100 total questions and you have no user data yet):
-- DELETE FROM questions;

WITH topic_map AS (
  SELECT id, name
  FROM topics
  WHERE name IN (
    'Algebra',
    'Advanced Math',
    'Geometry & Trigonometry',
    'Problem Solving & Data Analysis',
    'Reading Comprehension',
    'Grammar & Usage',
    'Vocabulary in Context',
    'Expression of Ideas'
  )
),
data AS (
  SELECT *
  FROM (VALUES
    -- =========================
    -- MATH (category_id = 1111...)
    -- =========================

    -- Algebra (15)
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If x + 9 = 21, what is the value of x?',
     '10','11','12','13','C',
     'To solve a one-step equation, undo the addition by subtracting 9 from both sides. x + 9 = 21 becomes x = 21 - 9. Performing the subtraction gives x = 12. Check by plugging back in: 12 + 9 = 21, so the solution is consistent.',
     1),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If 4x - 7 = 17, what is x?',
     '4','5','6','7','C',
     'First isolate the term with x by adding 7 to both sides: 4x = 24. Then divide both sides by 4 to get x = 6. A quick check confirms it: 4(6) - 7 = 24 - 7 = 17. This is the standard two-step linear equation process.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'What is the solution set to the inequality 3x + 2 > 14?',
     'x > 4','x > 6','x < 4','x < 6','A',
     'Subtract 2 from both sides to isolate the 3x term: 3x > 12. Then divide both sides by 3, which keeps the inequality direction the same because 3 is positive. This gives x > 4. The solution set includes all numbers greater than 4.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'A line has slope 3 and passes through the point (2, 5). What is the y-intercept of the line?',
     '1','-1','3','-3','B',
     'Use point-slope form: y - 5 = 3(x - 2). Expand: y - 5 = 3x - 6, so y = 3x - 1. In slope-intercept form y = mx + b, the y-intercept is b. Therefore the y-intercept is -1.',
     3),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If f(x) = 2x - 3, what is f(8)?',
     '10','13','16','19','B',
     'Evaluate a function by substituting the input value for x. Replace x with 8: f(8) = 2(8) - 3 = 16 - 3 = 13. A common mistake is to forget order of operations; you multiply before subtracting. The correct value is 13.',
     1),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'Solve the system: y = x + 4 and y = 2x - 1. What is x?',
     '3','4','5','6','A',
     'Because both expressions equal y, set them equal to each other: x + 4 = 2x - 1. Subtract x from both sides to get 4 = x - 1. Add 1 to both sides: x = 5. Then y = 9, but the question only asks for x.',
     3),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If (x/3) + 5 = 9, what is x?',
     '9','10','11','12','A',
     'Start by subtracting 5 from both sides to isolate the fraction: x/3 = 4. Then multiply both sides by 3 to undo the division: x = 12. This problem checks whether you can correctly reverse operations in the right order. Substitution confirms: 12/3 + 5 = 4 + 5 = 9.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'A store sells notebooks for $2 each plus a one-time $5 shipping fee. Which equation gives the total cost C for n notebooks?',
     'C = 2n','C = 5n + 2','C = 2n + 5','C = 2(n + 5)','C',
     'The total cost is the variable cost plus the fixed fee. The variable cost is $2 per notebook, which is 2n, and the fixed shipping fee is 5. Adding them gives C = 2n + 5. The expression 2(n + 5) would incorrectly multiply the shipping fee by 2.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If 5(x - 2) = 3x + 6, what is x?',
     '4','6','8','10','C',
     'Distribute: 5x - 10 = 3x + 6. Subtract 3x from both sides: 2x - 10 = 6. Add 10 to both sides: 2x = 16. Divide by 2: x = 8. A careful distribution step prevents the most common error.',
     3),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'Which expression is equivalent to 3(2x + 1) - 4x?',
     '2x + 3','2x - 3','6x + 3','6x - 3','A',
     'Distribute 3: 3(2x + 1) = 6x + 3. Then subtract 4x: (6x + 3) - 4x = 2x + 3. Combining like terms is the key step. The final simplified expression is 2x + 3.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If the average of x and 14 is 20, what is x?',
     '20','24','26','40','D',
     'Average of two numbers is their sum divided by 2: (x + 14)/2 = 20. Multiply both sides by 2 to remove the denominator: x + 14 = 40. Subtract 14: x = 26. The equation structure is common on SAT word problems involving averages.',
     2),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If g(x) = -3x + 2, for what value of x does g(x) = -10?',
     '2','3','4','5','D',
     'Set the function equal to -10: -3x + 2 = -10. Subtract 2 from both sides: -3x = -12. Divide by -3: x = 4. Pay attention to negatives; dividing by a negative changes signs but does not flip an equality.',
     3),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If x is an integer and 2x < 9, what is the greatest possible value of x?',
     '3','4','5','6','B',
     'Solve the inequality: 2x < 9 implies x < 4.5 after dividing by 2. Since x must be an integer, the largest integer less than 4.5 is 4. Always apply the integer condition after solving the inequality. Therefore, x = 4 is the greatest possible value.',
     3),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'Two consecutive integers have a sum of 41. What is the smaller integer?',
     '19','20','21','22','B',
     'Let the smaller integer be n and the next be n + 1. Their sum is n + (n + 1) = 41, so 2n + 1 = 41. Subtract 1 to get 2n = 40, then divide by 2: n = 20. The smaller integer is 20.',
     4),
    ('11111111-1111-1111-1111-111111111111','Algebra',
     'If (x - 1)(x + 1) = 48, what is the value of x^2?',
     '47','48','49','50','C',
     'Recognize the difference of squares: (x - 1)(x + 1) = x^2 - 1. So x^2 - 1 = 48. Add 1 to both sides to isolate x^2: x^2 = 49. The problem cleverly avoids solving for x directly.',
     4),

    -- Advanced Math (15)
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If f(x) = x^2 - 6x + 5, what is f(3)?',
     '-4','-2','2','4','B',
     'Substitute x = 3: f(3) = 3^2 - 6(3) + 5 = 9 - 18 + 5. Combine terms: 9 - 18 = -9, and -9 + 5 = -4. Carefully multiply before adding. The correct value is -4.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'Which expression is equivalent to (x^2 - 9)/(x - 3) for x != 3?',
     'x - 3','x + 3','x^2 - 3','x^2 + 3','B',
     'Factor the numerator as a difference of squares: x^2 - 9 = (x - 3)(x + 3). For x != 3, the (x - 3) cancels, leaving x + 3. The restriction x != 3 is important because the original expression is undefined at x = 3.',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If 3^(x) = 81, what is x?',
     '2','3','4','5','C',
     'Rewrite 81 as a power of 3: 81 = 3^4. If 3^x = 3^4, then x = 4 because equal bases imply equal exponents. This tests exponent matching, which is common in SAT advanced algebra. So x is 4.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'Solve: x^2 - 7x + 12 = 0',
     'x = 3 or x = 4','x = -3 or x = -4','x = 2 or x = 6','x = 1 or x = 12','A',
     'Factor the quadratic: x^2 - 7x + 12 = (x - 3)(x - 4). Set each factor equal to 0: x - 3 = 0 or x - 4 = 0. Therefore x = 3 or x = 4. Factoring is faster than the quadratic formula here.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If (x^2)^3 = x^12, which statement is true for all real x?',
     'Always true','Never true','Only true when x > 0','Only true when x != 0','A',
     'Use exponent rules: (x^2)^3 = x^(2*3) = x^6, not x^12. So the equation is not generally true. But notice the left side given is (x^2)^3, which equals x^6, meaning it equals x^12 only for special values (like x = 0, 1, -1). Therefore it is not true for all real x.',
     5),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If x^2 = 50, what is the value of x?',
     '5','-5','5sqrt(2) or -5sqrt(2)','sqrt(50) only','C',
     'Taking the square root of both sides gives x = ±sqrt(50). Simplify sqrt(50) = sqrt(25*2) = 5sqrt(2). Because squaring loses sign information, both positive and negative roots work. So x = 5sqrt(2) or x = -5sqrt(2).',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If (x - 2)^2 = 9, what are the possible values of x?',
     'x = 5','x = -1','x = 5 or x = -1','x = 3 or x = -3','C',
     'If (x - 2)^2 = 9, then x - 2 can be 3 or -3 because squaring either gives 9. So x - 2 = 3 gives x = 5, and x - 2 = -3 gives x = -1. Always include both cases when solving an equation with squares.',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'What is the value of (2x + 3)(2x - 3)?',
     '4x^2 - 9','4x^2 + 9','4x^2 - 6x - 9','4x^2 + 6x - 9','A',
     'This is a difference of squares pattern: (a + b)(a - b) = a^2 - b^2. Here, a = 2x and b = 3, so the product is (2x)^2 - 3^2 = 4x^2 - 9. Recognizing patterns saves time and reduces algebra errors.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If x^3 = 64, what is x?',
     '2','4','6','8','B',
     'Cube root both sides: x = cube_root(64). Since 4^3 = 64, x = 4. This is a basic exponent and root relationship. Always check: 4*4*4 = 64, confirming the answer.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'Simplify: (x^2 * x^5) / x^3 for x != 0',
     'x^4','x^5','x^7','x^10','B',
     'Combine exponents in the numerator: x^2 * x^5 = x^(2+5) = x^7. Then divide by x^3, which subtracts exponents: x^(7-3) = x^4. The restriction x != 0 prevents division by zero. So the simplified expression is x^4.',
     2),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If 2^(x) * 2^(3) = 2^(10), what is x?',
     '3','6','7','13','C',
     'When multiplying powers with the same base, add exponents: 2^x * 2^3 = 2^(x+3). Set x + 3 = 10 to match the exponent on the right side. Subtract 3 from both sides to get x = 7. This is a direct application of exponent rules.',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'For the quadratic y = x^2 - 4x + 1, what is the x-coordinate of the vertex?',
     '1','2','3','4','B',
     'For y = ax^2 + bx + c, the vertex x-coordinate is -b/(2a). Here a = 1 and b = -4, so -(-4)/(2*1) = 4/2 = 2. You can also complete the square to confirm. The vertex occurs at x = 2.',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If x is a solution to x^2 + x - 6 = 0, what are the possible values of x?',
     'x = -3 or x = 2','x = 3 or x = -2','x = -6 or x = 1','x = 6 or x = -1','A',
     'Factor the quadratic: x^2 + x - 6 = (x + 3)(x - 2). Set each factor equal to 0: x + 3 = 0 gives x = -3, and x - 2 = 0 gives x = 2. Factoring is the fastest method because the numbers multiply to -6 and add to 1.',
     3),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If (x - 4)/(x + 2) = 2, what is x (assuming x != -2)?',
     '2','4','6','8','C',
     'Multiply both sides by (x + 2) to clear the denominator: x - 4 = 2(x + 2). Expand: x - 4 = 2x + 4. Subtract x from both sides: -4 = x + 4. Subtract 4: x = -8.',
     4),
    ('11111111-1111-1111-1111-111111111111','Advanced Math',
     'If x + 1/x = 5, what is x^2 + 1/x^2?',
     '21','23','25','27','B',
     'Square both sides: (x + 1/x)^2 = x^2 + 2 + 1/x^2. Since x + 1/x = 5, the left side is 25. Then 25 = x^2 + 2 + 1/x^2, so x^2 + 1/x^2 = 23. This uses a standard algebra identity common in harder SAT problems.',
     5),

    -- Geometry & Trigonometry (15)
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A rectangle has length 12 and width 5. What is its area?',
     '17','30','60','120','C',
     'Area of a rectangle is length times width. Multiply 12 by 5 to get 60. Units would be square units if provided. This is a foundational geometry skill used in many SAT applications.',
     1),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A circle has diameter 10. What is its radius?',
     '2','5','10','20','B',
     'The radius is half the diameter. If the diameter is 10, divide by 2 to get 5. Many circle formulas use radius, so converting from diameter correctly is important. The radius is 5.',
     1),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'What is the circumference of a circle with radius 7?',
     '7pi','14pi','49pi','98pi','B',
     'Circumference is C = 2πr. Substitute r = 7: C = 2π(7) = 14π. Be careful not to confuse with area, which is πr^2. The circumference is 14π.',
     2),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'In a right triangle, one leg is 6 and the other leg is 8. What is the hypotenuse?',
     '10','12','14','16','A',
     'Use the Pythagorean theorem: a^2 + b^2 = c^2. Compute 6^2 + 8^2 = 36 + 64 = 100. Then c = sqrt(100) = 10. This is the classic 6-8-10 right triangle.',
     2),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'Two lines intersect to form vertical angles. If one angle measures 47 degrees, what is the measure of its vertical angle?',
     '43','47','133','180','B',
     'Vertical angles are opposite angles formed by two intersecting lines, and they are always congruent. That means they have the same measure. So if one vertical angle is 47 degrees, the angle opposite it is also 47 degrees. The correct measure is 47.',
     1),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'The sum of interior angles of a triangle is:',
     '90 degrees','180 degrees','270 degrees','360 degrees','B',
     'In Euclidean geometry, every triangle has interior angles that add to 180 degrees. This fact is used to solve many angle problems. You can visualize it by drawing a line parallel to one side and using alternate interior angles. The sum is always 180 degrees.',
     1),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A right triangle has an acute angle of 30 degrees. What is the other acute angle?',
     '30 degrees','45 degrees','60 degrees','90 degrees','C',
     'A triangle has 180 degrees total. A right triangle already has a 90-degree angle, so the remaining two angles sum to 90 degrees. If one acute angle is 30 degrees, the other is 60 degrees. This matches the common 30-60-90 triangle structure.',
     2),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'If a point is at (4, -3), what is its distance from the origin?',
     '5','7','1','sqrt(7)','A',
     'Distance from the origin uses the distance formula: sqrt(x^2 + y^2). Here, x = 4 and y = -3, so sqrt(4^2 + (-3)^2) = sqrt(16 + 9) = sqrt(25) = 5. Squaring removes the negative sign. The distance is 5.',
     3),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A cylinder has radius 3 and height 10. What is its volume?',
     '30pi','60pi','90pi','120pi','C',
     'Volume of a cylinder is V = πr^2h. Substitute r = 3 and h = 10: V = π(3^2)(10) = π(9)(10) = 90π. This formula is area of base times height, where the base is a circle. The volume is 90π.',
     3),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'In the coordinate plane, what is the slope of the line passing through (1, 2) and (5, 10)?',
     '1','2','3','4','B',
     'Use slope formula (y2 - y1)/(x2 - x1). Here it is (10 - 2)/(5 - 1) = 8/4 = 2. Slope represents change in y per unit change in x. Therefore the slope is 2.',
     2),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A triangle has side lengths 7, 24, and 25. Is it a right triangle?',
     'Yes, because 7^2 + 24^2 = 25^2','Yes, because 7 + 24 = 25','No, because 7^2 + 24^2 != 25^2','No, because all right triangles have equal legs','A',
     'Check the Pythagorean theorem using the largest side as the hypotenuse. Compute 7^2 + 24^2 = 49 + 576 = 625. Since 25^2 = 625, the equality holds, so it is a right triangle. This is a standard SAT test for right triangle identification.',
     4),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'The area of a triangle is 48 and its base is 12. What is the height?',
     '4','6','8','10','C',
     'Use the triangle area formula A = (1/2)bh. Substitute 48 = (1/2)(12)h = 6h. Divide both sides by 6 to get h = 8. Always isolate the height after simplifying. The height is 8.',
     2),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A line makes an angle of 45 degrees with the positive x-axis. What is its slope?',
     '0','1','sqrt(2)','2','B',
     'Slope equals tan(theta), where theta is the angle the line makes with the positive x-axis. For 45 degrees, tan(45) = 1. This is a key trig fact and connects geometry to coordinate slope. The slope is 1.',
     4),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'If two angles are complementary and one angle is 38 degrees, what is the other angle?',
     '52 degrees','62 degrees','142 degrees','180 degrees','A',
     'Complementary angles add to 90 degrees. If one is 38 degrees, subtract from 90: 90 - 38 = 52. This is different from supplementary angles, which add to 180. The complementary angle is 52 degrees.',
     1),
    ('11111111-1111-1111-1111-111111111111','Geometry & Trigonometry',
     'A square has perimeter 36. What is the area of the square?',
     '9','36','81','324','C',
     'Perimeter of a square is 4s, where s is the side length. If 4s = 36, then s = 9. Area is s^2, so area = 9^2 = 81. This uses two linked formulas and is common on SAT geometry.',
     3),

    -- Problem Solving & Data Analysis (15)
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A shirt originally costs $40 and is on sale for 25% off. What is the sale price?',
     '$10','$20','$30','$35','C',
     'A 25% discount means you pay 75% of the original price. Compute 0.75 * 40 = 30. Another method is to find 25% of 40 (which is 10) and subtract it: 40 - 10 = 30. The sale price is $30.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'If 60% of a number is 48, what is the number?',
     '60','70','80','90','C',
     'Translate the statement into an equation: 0.60n = 48. Divide both sides by 0.60: n = 48 / 0.60 = 80. You can also scale by fractions: 60% = 3/5, so (3/5)n = 48 implies n = 48*(5/3) = 80. The number is 80.',
     3),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A recipe uses 3 cups of flour for every 2 cups of sugar. If the recipe uses 9 cups of flour, how many cups of sugar are used?',
     '4','6','8','9','B',
     'This is a ratio problem: flour:sugar = 3:2. If flour is 9, that is 3 times 3, so scale the sugar by the same factor: 2 * 3 = 6. Proportions help: 3/2 = 9/s, so s = 6. The recipe uses 6 cups of sugar.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'The mean of 8 numbers is 15. What is the sum of the 8 numbers?',
     '23','60','120','150','D',
     'Mean = (sum)/(count). If the mean is 15 for 8 numbers, then sum = 15 * 8. Multiply: 15*8 = 120. The sum is 120. This type of mean-to-sum conversion appears frequently on SAT data questions.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A car travels 180 miles in 3 hours. What is its average speed in miles per hour?',
     '30','45','60','90','C',
     'Average speed is distance divided by time. Compute 180/3 = 60 miles per hour. This assumes constant average rate over the trip. The correct average speed is 60 mph.',
     1),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A box contains 5 red balls and 7 blue balls. What is the probability of picking a red ball?',
     '5/7','5/12','7/12','7/5','B',
     'Probability is favorable outcomes divided by total outcomes. Favorable outcomes (red) = 5. Total balls = 5 + 7 = 12. Therefore probability = 5/12. Always include all items in the denominator.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A student scored 78, 82, 90, and 100 on four tests. What is the median score?',
     '82','86','90','88','B',
     'Order the scores: 78, 82, 90, 100. With an even number of values, the median is the average of the two middle numbers. The middle two are 82 and 90, so median = (82 + 90)/2 = 86. The median is 86.',
     3),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A store increases a price from $50 to $60. What is the percent increase?',
     '10%','15%','20%','25%','C',
     'Percent increase = (increase/original) * 100%. The increase is 60 - 50 = 10. Divide by original: 10/50 = 0.2. Convert to percent: 0.2 = 20%. The percent increase is 20%.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'If the ratio of cats to dogs is 4:5 and there are 45 dogs, how many cats are there?',
     '20','32','36','40','D',
     'The ratio cats:dogs = 4:5 means cats = (4/5)*dogs. With 45 dogs, cats = (4/5)*45 = 4*9 = 36. Another way: 45 corresponds to 5 parts, so 1 part = 9 and cats are 4 parts = 36. The number of cats is 36.',
     3),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A data set has values 2, 3, 3, 7, 10. What is the mode?',
     '2','3','7','10','B',
     'The mode is the value that occurs most often. In the set, 3 appears twice while all other values appear once. That makes 3 the most frequent value. Therefore, the mode is 3.',
     1),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'If a quantity decreases from 200 to 150, what is the percent decrease?',
     '10%','20%','25%','50%','C',
     'Percent decrease = (decrease/original) * 100%. The decrease is 200 - 150 = 50. Divide by the original 200: 50/200 = 0.25. Convert to percent: 25%. The quantity decreased by 25%.',
     3),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A student answers 18 questions correctly out of 24. What percent is correct?',
     '60%','70%','75%','80%','C',
     'Convert to a fraction and then to a percent: 18/24 simplifies to 3/4 by dividing numerator and denominator by 6. 3/4 = 0.75, which is 75%. This is a common SAT fraction-to-percent conversion. The correct percent is 75%.',
     2),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A store sells pens for $1.50 each. If you buy 8 pens, what is the total cost?',
     '$9','$10','$12','$15','C',
     'Multiply price per item by number of items: 1.50 * 8. 1.5*8 = 12. You can compute 15*8 = 120 and then divide by 10. The total cost is $12.',
     1),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A train travels 210 miles in 3.5 hours. What is its average speed (mph)?',
     '50','60','70','80','C',
     'Average speed = distance/time = 210/3.5. Divide both numerator and denominator by 0.5: 210/3.5 = 420/7 = 60. This question checks comfort with decimals and fractions in rate problems. The average speed is 60 mph.',
     4),
    ('11111111-1111-1111-1111-111111111111','Problem Solving & Data Analysis',
     'A jar has 3 green, 4 red, and 5 yellow marbles. If one marble is chosen at random, what is the probability it is NOT red?',
     '4/12','8/12','3/12','5/12','B',
     'Total marbles = 3 + 4 + 5 = 12. Not red means green or yellow, which is 3 + 5 = 8 favorable outcomes. Probability = 8/12, which can simplify to 2/3, but 8/12 is the matching option. The probability it is not red is 8/12.',
     4),

    -- =========================
    -- READING & WRITING (category_id = 2222...)
    -- =========================

    -- Reading Comprehension (10)
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "In recent years, many cities have expanded bike lanes not only to reduce traffic, but also to improve public health." Which choice best states the main idea?',
     'Bike lanes are expensive to build in cities.','Bike lanes can serve multiple city goals beyond transportation.','Traffic problems are impossible to solve.','Public health depends only on exercise.',
     'B',
     'The sentence explains that bike lanes are expanded for more than one reason: reducing traffic and improving public health. That means the author is emphasizing multiple benefits, not cost or impossibility. Choice B captures the broader point: bike lanes support more than transportation needs. The other choices add claims the passage does not make.',
     2),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "Although the painting was once dismissed as ordinary, recent analysis revealed pigments that were rare for its time." What does the passage most strongly suggest?',
     'The painting was always considered valuable.','The painting may be more significant than originally believed.','Rare pigments always make art famous.','The painting was created recently.',
     'B',
     'The passage contrasts the painting being dismissed with new evidence that changes how it is viewed. Discovering rare pigments indicates the work may have been more intentional, costly, or historically important than people thought. Choice B matches that inference. The passage does not say it was always valuable or recently created.',
     3),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "The researcher repeated the experiment three times, each time adjusting a single variable, to isolate the cause of the unexpected result." What is the function of "each time adjusting a single variable"?',
     'To show the researcher was guessing randomly.','To explain how the researcher controlled the experiment.','To argue that experiments are unnecessary.','To suggest the result was expected.',
     'B',
     'The phrase explains the method: only one variable changes in each trial. That is a classic way to control an experiment because it helps identify which factor causes the outcome. Choice B captures the purpose of describing the method. The other choices contradict the careful approach described in the sentence.',
     3),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "Some historians argue the treaty ended the conflict, while others note that violence continued in smaller forms for decades." Which choice best describes the relationship between the two claims?',
     'They are unrelated topics.','They present contrasting perspectives about the treaty impact.','They both fully support the treaty.','They state identical conclusions.',
     'B',
     'The first group claims the treaty ended the conflict, while the second group points out that violence continued. Those statements conflict in how they evaluate the treaty effectiveness. That is a contrast in interpretation. Therefore, choice B is the best description.',
     2),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "The novel uses an unreliable narrator, forcing readers to question whether the events happened as described." What is implied by "unreliable narrator"?',
     'The narrator tells the story from multiple timelines.','The narrator may not be fully truthful or accurate.','The narrator is the author of the book.','The narrator provides only scientific facts.',
     'B',
     'An unreliable narrator is one whose account cannot be fully trusted, often because of bias, limited knowledge, or deception. The passage directly says readers must question the events, which matches uncertainty about accuracy. Choice B is the standard meaning and fits the context. The other choices do not connect to the idea of trustworthiness.',
     3),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "When the company introduced flexible schedules, employee turnover decreased noticeably within six months." Which inference is best supported?',
     'Flexible schedules may have improved employee satisfaction.','Turnover decreased because salaries doubled.','Employees worked fewer hours overall.','The company stopped hiring new employees.',
     'A',
     'The passage states turnover decreased after flexible schedules were introduced. A reasonable inference is that employees were more willing to stay because the change improved their work-life balance or satisfaction. The passage does not mention salaries, hours, or hiring freezes. So A is supported while the others introduce unsupported causes.',
     2),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "The scientist cautioned that the findings were preliminary and should be tested with larger samples." Why does the scientist caution this?',
     'To claim the findings are definitely false.','To emphasize the need for further verification.','To argue that sample size never matters.','To suggest the study was unethical.',
     'B',
     'Calling findings preliminary signals they are early results that might change with more data. Mentioning larger samples points to statistical reliability and reducing random error. The caution is about verification and strengthening the evidence. Choice B matches that reasoning; the other options misrepresent the purpose of scientific caution.',
     3),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "Because the river floods each spring, farmers plant crops that can tolerate temporary waterlogging." Which detail best supports the cause-and-effect relationship?',
     'Farmers dislike planting in the spring.','The river floods each spring.','Crops grow in many climates.','Waterlogging always improves soil.',
     'B',
     'The sentence establishes a cause (spring flooding) and an effect (choosing water-tolerant crops). The detail that directly supports the cause is the flooding itself. Choice B restates the cause. The other options are unrelated or introduce claims not present in the passage.',
     2),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "The musician blended classical structures with modern rhythms, creating a sound that appealed to diverse audiences." What is the best summary?',
     'The musician rejected all classical music.','Mixing styles helped the musician reach many listeners.','Modern rhythms are always better than classical.','Audiences dislike music that blends genres.',
     'B',
     'The passage highlights a combination of classical and modern elements and links that blend to broader appeal. That means the key idea is that mixing styles widened the audience. Choice B captures both the method (mixing styles) and result (diverse audiences). The other choices contradict or exaggerate the passage.',
     2),
    ('22222222-2222-2222-2222-222222222222','Reading Comprehension',
     'Passage: "The author begins with a personal anecdote before presenting statistics about the issue." Why might the author do this?',
     'To confuse the reader with unrelated stories.','To engage the reader emotionally before providing evidence.','To prove statistics are unnecessary.','To avoid supporting the argument.',
     'B',
     'Personal anecdotes can hook the reader and make an issue feel relatable. After interest is built, statistics provide evidence and credibility. The combination of story then data is a common persuasive structure. Choice B explains that strategy clearly, while the other answers misinterpret the author purpose.',
     3),

    -- Grammar & Usage (10)
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which sentence is grammatically correct?',
     'Me and my friend are studying.','My friend and I are studying.','My friend and me are studying.','I and my friend is studying.',
     'B',
     'When pronouns are part of the subject, use subject pronouns like "I" rather than object pronouns like "me." Also, standard English places the other person first: "My friend and I." The verb should agree with the compound subject ("are"). Therefore, choice B is correct.',
     1),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Choose the best punctuation: The students finished the project____ they submitted it early.',
     '.,',';',' :','--',
     'B',
     'Both halves are complete independent clauses: "The students finished the project" and "they submitted it early." A semicolon correctly joins two related independent clauses without a conjunction. A period would require splitting into two sentences, and a colon or dash is not the best standard choice here. Therefore, the semicolon is correct.',
     3),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which choice best corrects the sentence? "Each of the players have a locker."',
     'Each of the players have a locker.','Each of the players has a locker.','Each of the players were given a locker.','Each of the players are having a locker.',
     'B',
     'The subject is "Each," which is singular, even though it refers to a group. Singular subjects take singular verbs, so "has" is correct, not "have." This is a common SAT subject-verb agreement trap because the phrase "of the players" is distracting. Choice B fixes the agreement properly.',
     2),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which revision best fixes the modifier error? "Walking down the street, the trees looked beautiful."',
     'Walking down the street, the trees looked beautiful.','Walking down the street, I thought the trees looked beautiful.','The trees, walking down the street, looked beautiful.','Walking down, the street looked beautiful to the trees.',
     'B',
     'The opening phrase "Walking down the street" must describe the person doing the walking. In the original sentence, it incorrectly modifies "the trees," creating a dangling modifier. Choice B adds the correct subject ("I"), making the sentence logically clear and grammatically correct. The other choices either keep the error or create nonsense.',
     4),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Choose the best correction: "The committee, along with the coach, are meeting today."',
     'are','is','were','be',
     'B',
     'The true subject is "committee," which is singular. The phrase "along with the coach" is a parenthetical phrase and does not change the subject number. Therefore, the verb must be singular: "is meeting today." SAT questions often test this by placing extra phrases between subject and verb.',
     3),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which choice correctly uses a comma?',
     'After dinner we went for a walk.','After dinner, we went for a walk.','After, dinner we went for a walk.','After dinner we, went for a walk.',
     'B',
     'An introductory prepositional phrase like "After dinner" is commonly followed by a comma when it helps readability. Choice B places the comma after the full introductory phrase, which is standard and clear. The other options place commas incorrectly or omit it in a way that is less clear. Therefore, B is correct.',
     1),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which sentence avoids a run-on?',
     'I wanted to study, I was tired.','I wanted to study I was tired.','I wanted to study, but I was tired.','I wanted to study, and was tired.',
     'C',
     'A run-on happens when two independent clauses are joined incorrectly. "I wanted to study" and "I was tired" are both independent clauses, so you need a semicolon, period, or a comma with a conjunction. Choice C correctly uses a comma plus the coordinating conjunction "but." That structure fixes the run-on.',
     2),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which option best corrects the pronoun agreement? "A student should bring their laptop."',
     'A student should bring their laptop.','A student should bring his or her laptop.','Students should bring his laptop.','A student should bring there laptop.',
     'B',
     'The singular noun "A student" should match with a singular pronoun in formal standard usage. "His or her" maintains agreement and avoids the mismatch between singular and plural. Choice D uses the wrong word ("there"), and choice C is incorrect agreement. Therefore, B is the best correction.',
     3),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Choose the best correction: "The data shows a clear trend."',
     'shows','show','showing','to show',
     'B',
     'In many formal contexts, "data" is treated as plural (like "results"), so the plural verb "show" is preferred. SAT tends to test standard academic usage, where plural agreement is expected. Therefore "The data show a clear trend" is the best option here. Choice B fixes the agreement.',
     4),
    ('22222222-2222-2222-2222-222222222222','Grammar & Usage',
     'Which sentence uses the apostrophe correctly?',
     'The dogs bone was missing.','The dog''s bone was missing.','The dogs'' bone was missing.','The dog bone''s was missing.',
     'B',
     'A singular noun showing possession takes apostrophe + s: dog''s. "Dog''s bone" means the bone belonging to one dog. "Dogs''" would indicate possession by multiple dogs, and "dogs" without an apostrophe is just plural. Therefore, choice B uses the apostrophe correctly.',
     2),

    -- Vocabulary in Context (10)
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The coach was elated after the team won," the word "elated" most nearly means:',
     'confused','thrilled','angry','careless','B',
     'Context clues show a positive emotion after a win. "Elated" means extremely happy or excited. Words like confused or angry do not match the situation. Therefore, the best meaning is thrilled.',
     1),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "Her argument was concise, yet persuasive," "concise" most nearly means:',
     'long-winded','brief','uncertain','inaccurate','B',
     'The phrase "yet persuasive" suggests the argument was short but still effective. "Concise" means brief and to the point, not long-winded. The other options describe accuracy or certainty rather than length and clarity. Therefore, "brief" is correct.',
     2),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The student was diligent about completing assignments on time," "diligent" most nearly means:',
     'lazy','careful and hardworking','forgetful','impatient','B',
     'Completing assignments on time consistently suggests strong effort and responsibility. "Diligent" describes someone who works carefully and persistently. It is the opposite of lazy and does not mean forgetful. Therefore, the best match is careful and hardworking.',
     2),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The new rule was implemented to mitigate risk," "mitigate" most nearly means:',
     'increase','ignore','reduce','predict','C',
     'Risk mitigation means making risk smaller or less severe. So "mitigate" means reduce. The other options either make risk worse or do not change it. Therefore, reduce is the correct meaning.',
     3),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The scientist remained skeptical of the early results," "skeptical" most nearly means:',
     'certain','doubtful','excited','silent','B',
     'If someone is skeptical, they do not fully trust a claim without more evidence. The phrase "early results" also suggests caution. So skeptical most closely means doubtful. The other choices do not reflect uncertainty.',
     3),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The policy was amended after public feedback," "amended" most nearly means:',
     'copied','changed','ignored','destroyed','B',
     'When a policy is amended, it is revised or changed, often to improve it. Public feedback leading to amendment suggests adjustments were made. Copied, ignored, and destroyed do not fit the context. Therefore, changed is correct.',
     2),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The speaker delivered an eloquent speech," "eloquent" most nearly means:',
     'well-spoken','awkward','silent','boring','A',
     'An eloquent speech is expressed clearly and persuasively, usually with strong language and flow. That matches "well-spoken." Awkward and boring do not match the positive description, and silent is unrelated. Therefore, well-spoken is correct.',
     2),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The plan was feasible given the time and budget," "feasible" most nearly means:',
     'possible','dangerous','unnecessary','unclear','A',
     'If a plan is feasible, it can realistically be done. The phrase "given the time and budget" signals practicality, which matches possible. The other options do not match the meaning of doable or realistic. Therefore, possible is correct.',
     3),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The professor''s remarks were ambiguous," "ambiguous" most nearly means:',
     'clear','confusing','rude','funny','B',
     'Ambiguous statements have more than one possible meaning or are not clear. That can confuse listeners because they cannot determine the intended message. Clear is the opposite, and rude or funny describe tone rather than clarity. Therefore, confusing is correct.',
     3),
    ('22222222-2222-2222-2222-222222222222','Vocabulary in Context',
     'In the sentence "The child was reluctant to try the new food," "reluctant" most nearly means:',
     'eager','unwilling','proud','carefree','B',
     'Reluctant means hesitant or not willing to do something. The context of trying a new food fits unwillingness. Eager is the opposite, and proud or carefree are unrelated. Therefore, unwilling is correct.',
     1),

    -- Expression of Ideas (10)
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Choose the best transition: "The experiment was difficult to set up. ____ , the results were worth the effort."',
     'However','For example','Meanwhile','Because','A',
     'The second sentence contrasts difficulty with a positive outcome. A contrast transition like "However" shows that despite the difficulty, the results were valuable. "For example" introduces an example, and "Meanwhile" indicates time, not contrast. Therefore, "However" is best.',
     2),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which sentence best adds evidence to support the claim "Regular sleep improves focus in students"?',
     'Sleep is something everyone does.','Many students enjoy staying up late.','A study found students who slept 8 hours performed better on attention tasks.','Focus can mean different things.',
     'C',
     'To support a claim, you need specific evidence. Choice C provides a study result that directly connects sleep duration to better attention performance. The other choices are general or off-topic and do not prove the claim. Therefore, C is the strongest supporting sentence.',
     3),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which revision best improves clarity? "The program helped students, which was beneficial."',
     'The program helped students, which was beneficial.','The program helped students by providing tutoring after school.','The program helped students, beneficially.','The program, students, and benefits were all connected.',
     'B',
     'Clarity improves when vague words are replaced with specific details. "Which was beneficial" is unclear because it does not explain how or why. Choice B specifies the mechanism: tutoring after school. That makes the sentence more informative and easier to understand.',
     2),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Choose the best concluding sentence: "In summary, public transportation reduces traffic and pollution."',
     'Cars are common in many cities.','Therefore, investing in reliable transit can improve city life.','Pollution has many causes.','Some people like walking.',
     'B',
     'A conclusion should follow logically from the summary and often suggests an implication or next step. If transit reduces traffic and pollution, it makes sense to recommend investing in it. Choice B connects the benefits to a practical conclusion. The other choices are unrelated or too general.',
     2),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which sentence best introduces the topic of a paragraph about time management?',
     'Time exists for everyone.','Managing time well helps students balance school, work, and rest.','Clocks are used worldwide.','Some people dislike schedules.',
     'B',
     'An introduction should state the main idea clearly and set up the paragraph focus. Choice B directly defines why time management matters and previews key areas (school, work, rest). The other options are either too vague or irrelevant. Therefore, B is the best topic sentence.',
     2),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Choose the best transition: "The first solution was expensive. ____ , it saved time in the long run."',
     'As a result','In contrast','For instance','Similarly','A',
     'The second clause explains a consequence or benefit that follows from the first idea. "As a result" signals that the outcome relates to the situation described. "In contrast" would emphasize opposition, and "Similarly" implies sameness. Therefore, "As a result" fits best here.',
     3),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which revision best removes redundancy? "The reason is because it was raining."',
     'The reason is because it was raining.','The reason is that it was raining.','Because the reason, it was raining.','The reason is due to because it was raining.',
     'B',
     'The phrase "reason is because" is redundant because "because" already implies a reason. A clearer structure is "The reason is that..." which avoids repeating the same idea. Choice B keeps the sentence grammatical and concise. Therefore, B is the best revision.',
     3),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which sentence best fits after this one? "The library extended its weekend hours."',
     'Many students said the change made it easier to study for exams.','Books can be expensive.','Some libraries have cafes.','Hours are measured in minutes.',
     'A',
     'A follow-up sentence should logically explain the impact or provide relevant supporting detail. If the library extended hours, it makes sense to discuss how students benefited. Choice A directly connects the change to study habits and exam preparation. The other options are not relevant.',
     2),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Choose the best word to maintain a formal tone: "The results were really good."',
     'really','super','very','highly','D',
     'Formal academic tone avoids casual intensifiers like "really" or slang like "super." "Highly" is a more formal adverb that fits academic writing, especially when describing quality (highly effective, highly significant). Therefore, replacing with "highly" best maintains a formal tone.',
     4),
    ('22222222-2222-2222-2222-222222222222','Expression of Ideas',
     'Which revision best improves organization? "First, the study explains the problem. It also gives background. Finally, it presents results. The background helps define key terms."',
     'Keep as is.','Move "The background helps define key terms" after "It also gives background."','Move "Finally, it presents results" to the beginning.','Delete the sentence about key terms.',
     'B',
     'Organization improves when related sentences are grouped together. The sentence about key terms clearly belongs with the background discussion. Placing it immediately after the background sentence creates a smoother flow and clearer structure. Therefore, moving it after "It also gives background" is best.',
     4)

    -- NOTE: This script inserts 100 rows total in the full version.
    -- If you want me to also include the remaining 50 rows (to reach a full 100 in this exact block),
    -- tell me and I will paste "Part 2" immediately (SQL Editor accepts running in two chunks).
  ) AS v(category_id, topic_name, question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty)
)
INSERT INTO questions (
  category_id,
  topic_id,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_answer,
  explanation,
  difficulty
)
SELECT
  d.category_id,
  t.id,
  d.question_text,
  d.option_a,
  d.option_b,
  d.option_c,
  d.option_d,
  d.correct_answer,
  d.explanation,
  d.difficulty
FROM data d
JOIN topic_map t
  ON t.name = d.topic_name;
